# Generated by Django 2.2.11 on 2021-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0002_account_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='t',
            field=models.IntegerField(default=0),
        ),
    ]
