# Generated by Django 2.2.11 on 2021-03-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0003_queue_t'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='account_id',
            new_name='account',
        ),
    ]
