# Generated by Django 2.2.11 on 2021-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0004_auto_20210329_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='t',
        ),
        migrations.AddField(
            model_name='queue',
            name='templet_id',
            field=models.IntegerField(default=1),
        ),
    ]
