# Generated by Django 2.2.11 on 2021-04-01 10:57

from django.db import migrations, models
import django.db.models.deletion
import fresh.models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0005_auto_20210329_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templet_id', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fresh.Account')),
            ],
            bases=(fresh.models.StrMixin, models.Model),
        ),
    ]
