version: "3.9"

services:
  postgresdb:
    image: postgres:13.3
    volumes:
      - postgres-db-data:/var/lib/postgresql/
    expose:
      - 5432
    env_file:
      - .docker-services-envs/prod/postgresdb.env
  web:
    build: .
    depends_on:
      - postgresdb
    command: bash -c "python manage.py collectstatic && python .scripts/wait_db.py && python manage.py migrate && gunicorn Dockerify.wsgi:application --bind 0.0.0.0:8000"
    volumes:
    - static-files:/app/staticfiles/
    - media-files:/app/mediafiles/
    expose:
      - 8000
    env_file:
      - .docker-services-envs/prod/web.env
  nginx:
    build: ./.nginx/
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
    - static-files:/home/app/web/staticfiles/
    - media-files:/home/app/web/mediafiles/

volumes:
  postgres-db-data:
  static-files:
  media-files:
