version: "3.9"

services:
  postgresdb:
    image: postgres:13.3
    volumes:
      - postgres-db-data:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=dockerify
      - POSTGRES_USER=dockerify_api
      - POSTGRES_PASSWORD=cyneta-suspega-korel
    ports:
      - 8432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgresdb

volumes:
  postgres-db-data:
