# Generated by Django 2.2.11 on 2020-09-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoxxCard',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('metacard_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='foxx', serialize=False, to='plant.MetaCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LianaCard',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('metacard_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='liana', serialize=False, to='plant.MetaCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoxxDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant.FoxxCard')),
            ],
        ),
    ]
