# Generated by Django 2.2.11 on 2020-09-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foxxdisplay',
            name='card',
        ),
        migrations.RemoveField(
            model_name='lianacard',
            name='metacard_ptr',
        ),
        migrations.DeleteModel(
            name='FoxxCard',
        ),
        migrations.DeleteModel(
            name='FoxxDisplay',
        ),
        migrations.DeleteModel(
            name='LianaCard',
        ),
        migrations.DeleteModel(
            name='MetaCard',
        ),
    ]
