# Generated by Django 3.2.4 on 2021-07-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='segment',
            table='segment',
        ),
    ]
