# Generated by Django 3.1.4 on 2020-12-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70)),
                ('provider', models.CharField(blank=True, max_length=45, null=True)),
                ('public_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metacard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=255)),
                ('is_delinquent', models.BooleanField()),
                ('uid', models.CharField(max_length=45)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clover.currency')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clover.language')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('ctype', models.CharField(max_length=45)),
                ('category', models.CharField(blank=True, max_length=70, null=True)),
                ('shopname', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clover.contact')),
                ('metacard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metashop', to='clover.metacard')),
            ],
        ),
        migrations.AddField(
            model_name='metacard',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clover.region'),
        ),
        migrations.CreateModel(
            name='Clover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(unique=True)),
                ('ctype', models.CharField(max_length=45)),
                ('card_id', models.IntegerField(null=True, unique=True)),
                ('card_pid', models.CharField(max_length=45, null=True, unique=True)),
                ('card_uid', models.CharField(max_length=45, null=True, unique=True)),
                ('lattice_id', models.IntegerField(null=True, unique=True)),
                ('shop_handle', models.CharField(max_length=255, unique=True)),
                ('is_arrow_active', models.BooleanField(null=True)),
                ('is_bamboo_active', models.BooleanField(null=True)),
                ('is_foxx_active', models.BooleanField(null=True)),
                ('is_liana_active', models.BooleanField(null=True)),
                ('is_lotus_active', models.BooleanField(null=True)),
                ('is_poppy_active', models.BooleanField(null=True)),
                ('is_snow_active', models.BooleanField(null=True)),
                ('is_ultimate_active', models.BooleanField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clover.currency')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clover.language')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clover.region')),
            ],
        ),
    ]
