"""
Django settings for Djangotest project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(#m^w!b0s%!flv$%d!!o!b!@qg!efyjc+bcdt!w5ot)#pf1z4x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'base',
    'plant',
    'braintreepay',
    'fresh',
    'audience',
    'campaign',

    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'Djangotest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Djangotest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'djangotest',
        'USER': 'yannick',
        'PASSWORD': 'yannick',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# LOGGING = {
#      'version': 1,
#      'disable_existing_loggers': False,
#      'formatters': {
#         'simple': {
#             'format': '%(asctime)s HOSTNAME APP_NAME: %(message)s',
#             'datefmt': '%Y-%m-%dT%H:%M:%S',
#         },
#      },
#      'handlers': {
#          'file': {
#              'level': 'INFO',
#              'class': 'logging.FileHandler',
#              'filename': '/home/petitnokoue/Desktop/logging/djangotest-app.log',
#          },
#          'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#          },
#          'SysLog': {
#             'level': 'INFO',
#             'class': 'logging.handlers.SysLogHandler',
#             'formatter': 'simple',
#             'address': ('logs6.papertrailapp.com', 10439)
#          },
#      },
#      'loggers': {
#          # 'django': {
#          #     'handlers': ['file'],
#          #     'level': 'INFO',
#          #     'propagate': True,
#          # },
#          'app-logger': {
#             'handlers': ['SysLog'],
#             'level': 'CRITICAL',
#             'propagate': True,
#          },
#      },
# }

LOGGING = {
     'version': 1,
     'disable_existing_loggers': False,
     'formatters': {
        'simple': {
            'format': '%(asctime)s %(name)s : %(levelname)s : %(message)s [%(pathname)s; Line %(lineno)d]',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
     },
     'handlers': {
         'sys_log': {
            'level': 'INFO',
            'class': 'logging.handlers.SysLogHandler',
            'formatter': 'simple',
            'address': ('logs6.papertrailapp.com', 10439)
         },
         'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
         },
     },
     'loggers': {
         'app_logger': {
            'handlers': ['sys_log', 'console'],
            'level': 'DEBUG',
            'propagate': True,
         },
     },
}
