# Generated by Django 2.2.11 on 2020-06-16 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 18, 50, 24, 85634, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
