# Generated by Django 2.2.11 on 2020-07-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_suggested',
            field=models.DateTimeField(null=True),
        ),
    ]
