# Generated by Django 2.2.11 on 2020-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200820_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants_count',
            field=models.IntegerField(default=0),
        ),
    ]
