# Generated by Django 2.2.11 on 2020-08-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_metacard_trelliscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.Metacard'),
        ),
        migrations.AddField(
            model_name='product',
            name='trellis_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.TrellisCard'),
        ),
    ]
