# Generated by Django 2.2.11 on 2020-08-27 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bounced_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
    ]
