# Generated by Django 2.2.11 on 2020-08-31 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Place'),
        ),
    ]
