# Generated by Django 2.2.11 on 2020-09-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200831_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoxxCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('metacard_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='foxx', to='base.MetaCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LianaCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('metacard_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='liana', to='base.MetaCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.MetaCard'),
        ),
        migrations.AlterField(
            model_name='trelliscard',
            name='metacard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trellis', to='base.MetaCard'),
        ),
        migrations.CreateModel(
            name='FoxxDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.FoxxCard')),
            ],
        ),
    ]
