# Generated by Django 2.2.11 on 2020-09-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20200901_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foxxcard',
            name='metacard_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='foxx', serialize=False, to='base.MetaCard'),
        ),
        migrations.AlterField(
            model_name='lianacard',
            name='metacard_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='liana', serialize=False, to='base.MetaCard'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.MetaCard'),
        ),
        migrations.AlterField(
            model_name='trelliscard',
            name='metacard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trellis', to='base.MetaCard'),
        ),
    ]
