# Generated by Django 2.2.11 on 2020-09-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200901_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foxxdisplay',
            name='card',
        ),
        migrations.RemoveField(
            model_name='lianacard',
            name='metacard_ptr',
        ),
        migrations.AlterField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.MetaCard'),
        ),
        migrations.AlterField(
            model_name='trelliscard',
            name='metacard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trellis', to='base.MetaCard'),
        ),
        migrations.DeleteModel(
            name='FoxxCard',
        ),
        migrations.DeleteModel(
            name='FoxxDisplay',
        ),
        migrations.DeleteModel(
            name='LianaCard',
        ),
    ]
