# Generated by Django 2.2.11 on 2020-10-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20200901_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.MetaCard'),
        ),
        migrations.AlterField(
            model_name='trelliscard',
            name='metacard',
            field=models.IntegerField(),
        ),
    ]
