# Generated by Django 2.2.11 on 2020-10-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20201007_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trelliscard',
            old_name='metacard',
            new_name='metacard_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.MetaCard'),
        ),
    ]
