# Generated by Django 2.2.11 on 2020-11-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20201008_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metacard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='base.MetaCard'),
        ),
    ]
