version: "3.9"


x-service-django: &django
  build:
    context: .
    dockerfile: ./compose/dev/django/Dockerfile
    network: host
  depends_on:
    - postgres
  volumes:
    - .:/app
  env_file:
    - ./compose/dev/postgres/.env
    - ./compose/dev/django/.env


services:

  postgres:
    image: postgres:13.3
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - ./compose/dev/postgres/.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"

  rabbitmq_remote:
    image: rabbitmq:3-management
    container_name: rabbitmq_remote

  web:
    <<: *django
    container_name: web
    depends_on:
      - postgres
      - rabbitmq  # to delay asynchronous tasks
    ports:
      - "8000:8000"
    command: bash ./compose/dev/django/web/start.sh

  cron:
    <<: *django
    container_name: cron
    depends_on:
      - postgres
      - rabbitmq
    command: bash ./compose/dev/django/celery/cron/start.sh

  flower:
    <<: *django
    container_name: flower
    depends_on:
      - cron
    ports:
      - "5555:5555"
    command: bash ./compose/dev/django/celery/flower/start.sh

  consumer:
    <<: *django
    container_name: consumer
    depends_on:
      - rabbitmq_remote
      - postgres
    command: bash ./compose/dev/django/celery/consumer/start.sh


volumes:
  postgres_data:
