version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker-compose/prod/web/Dockerfile
    volumes:
      - static-files:/app/staticfiles/
      - media-files:/app/mediafiles/
    expose:
      - 8000
    env_file:
      - ./docker-compose/prod/web/.env
    command: bash ./docker-compose/prod/web/start.sh
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: ./docker-compose/prod/nginx-proxy/Dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static-files:/app/staticfiles/
      - media-files:/app/mediafiles/
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    env_file:
      - ./docker-compose/prod/nginx-proxy-ssl/.env
    depends_on:
      - nginx-proxy

volumes:
  static-files:
  media-files:
  certs:
  html:
  vhost:
  acme:
