version: "3.9"


x-service-django: &django
  build:
    context: .
    dockerfile: ./compose/dev/django/Dockerfile
    network: host
  depends_on:
    - postgres
  volumes:
    - .:/app
  env_file:
    - ./compose/dev/postgres/.env
    - ./compose/dev/django/.env


services:

  postgres:
    image: postgres:13.3
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - ./compose/dev/postgres/.env

  redis:
    image: redis:5.0
    container_name: redis

  web:
    <<: *django
    container_name: web
    ports:
      - "8000:8000"
    command: bash ./compose/dev/django/web/start.sh

  celeryworker:
    <<: *django
    container_name: celery_worker
    depends_on:
      - postgres
      - redis
    command: bash ./compose/dev/django/celery/worker/start.sh

  celeryflower:
    <<: *django
    container_name: celery_flower
    depends_on:
      - celeryworker
    ports:
      - "5555:5555"
    command: bash ./compose/dev/django/celery/flower/start.sh


volumes:
  postgres_data:
