version: "3.9"

services:
  postgresdb:
    image: postgres:13.3
    volumes:
      - postgres-db-data:/var/lib/postgresql/
    expose:
      - 5432
    env_file:
      - ./docker-compose/dev/postgresdb/.env
  web:
    build:
      context: .
      dockerfile: ./docker-compose/dev/web/Dockerfile
      network: host
    depends_on:
      - postgresdb
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./docker-compose/dev/web/.env
    command: bash ./docker-compose/dev/web/start.sh

volumes:
  postgres-db-data:
