version: "3.9"


x-service-django: &django
  build:
    context: .
    dockerfile: ./compose/prod/django/Dockerfile
  env_file:
    - ./compose/prod/django/.env


services:

  redis:
    image: redis:5.0
    container_name: redis

  web:
    <<: *django
    container_name: web
    env_file:
      - ./compose/prod/django/.env
      - ./compose/prod/django/web/proxy.env
    command: bash ./compose/prod/django/web/start.sh
    expose:
      - "8000"
    volumes:
      - static_files:/app/staticfiles/
      - media_files:/app/mediafiles/

  celeryworker:
    <<: *django
    container_name: celery_worker
    depends_on:
      - redis
    command: bash ./compose/prod/django/celery/worker/start.sh

  celeryflower:
    <<: *django
    container_name: celery_flower
    depends_on:
      - celeryworker
    env_file:
      - ./compose/prod/django/.env
      - ./compose/prod/django/celery/flower/proxy.env
    command: bash ./compose/prod/django/celery/flower/start.sh
    expose:
      - "5555"

  nginxproxy:
    container_name: nginx_proxy
    build:
      context: .
      dockerfile: ./compose/prod/nginx/proxy/Dockerfile
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - celeryflower
      - web
    volumes:
      - static_files:/app/staticfiles/
      - media_files:/app/mediafiles/
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginxproxyssl:
    container_name: nginx_proxy_ssl
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./compose/prod/nginx/ssl/.env
    depends_on:
      - nginxproxy
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh


volumes:
  static_files:
  media_files:
  certs:
  html:
  vhost:
  acme:
